"""gravatar

Revision ID: 498577b3b554
Revises: 
Create Date: 2018-03-13 08:09:39.556000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498577b3b554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
